# Generated by Django 2.2.5 on 2019-09-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('channel', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=10)),
                ('os', models.CharField(max_length=10)),
                ('impressions', models.IntegerField(null=True)),
                ('clicks', models.IntegerField(null=True)),
                ('installs', models.IntegerField()),
                ('spend', models.FloatField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
