# Generated by Django 2.2.5 on 2019-09-21 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
